config/routes.rb
if RAILS_ENV == "test"
  class ContentBlock
    def self.versioned?; true; end
    def self.publishable?; true; end
    def self.connectable?; true; end
    def self.searchable?; false; end
  end
end      

# For BrowserCMS Core testing. These routes should not be used by projects that use BrowserCMS as a gem.
# Only load these routes if this is the "root" application
#
if RAILS_ROOT == File.expand_path(File.dirname(__FILE__) + "/..")
  ActionController::Routing::Routes.draw do |map|
    map.connect "/__test__", :controller => "cms/content", :action => "show_page_route"

    # These are for testing and might need to be stripped out.
    map.connect "/tests/restricted", :controller => "tests/pretend", :action => "restricted"
    map.connect "/tests/open", :controller => "tests/pretend", :action => "open"
    map.connect "/tests/open_with_layout", :controller => "tests/pretend", :action => "open_with_layout"
    map.connect "/tests/error", :controller => "tests/pretend", :action => "error"
    map.connect "/tests/not-found", :controller => "tests/pretend", :action => "not_found"

    # Core CMS routes
    map.routes_for_browser_cms
  end
end

app/models/group.rb
#
# A group represents a collection of permissions. Each User can be assigned to one or more groups, and the sum of
# their permissions from all groups combined represents what they can do.
#
class Group < ActiveRecord::Base

  GUEST_CODE = "guest"

  has_many :user_group_memberships
  has_many :users, :through => :user_group_memberships
  
  has_many :group_permissions
  has_many :permissions, :through => :group_permissions
  
  has_many :group_sections
  has_many :sections, :through => :group_sections
  
  belongs_to :group_type
    
  validates_presence_of :name
  
  named_scope :named, lambda{|n| {:conditions => {:name => n}}}
  named_scope :with_code, lambda{|c| {:conditions => {:code => c}}}
    
  named_scope :public, :include => :group_type, :conditions => ["group_types.cms_access = ?", false]
  named_scope :cms_access, :include => :group_type, :conditions => ["group_types.cms_access = ?", true]
  
  def guest?
    group_type && group_type.guest?
  end
  
  def cms_access?
    group_type && group_type.cms_access?
  end

  # Finds the guest group, which is a special group that represents public non-logged in users.
  def self.guest
    with_code(GUEST_CODE).first
  end

end

app/controllers/cms/application_controller.rb
class Cms::ApplicationController < ApplicationController
  include Cms::Authentication::Controller
  include Cms::ErrorHandling
  include Cms::DomainSupport

  helper Cms::ApplicationHelper
  helper Cms::FormTagHelper
  include Cms::PathHelper
  helper Cms::PathHelper
  include Cms::PageHelper
  helper Cms::PageHelper
  helper Cms::MenuHelper
  helper Cms::RenderingHelper
  
  protected
    def escape_javascript(javascript)
      (javascript || '').gsub('\\','\0\0').gsub('</','<\/').gsub(/\r\n|\n|\r/, "\\n").gsub(/["']/) { |m| "\\#{m}" }
    end
  
    def redirect_to_first(*urls)
      urls.each do |url|
        unless url.blank?
          return redirect_to(url)
        end
      end
    end
    
    def current_site
      @current_site ||= Site.find_by_domain(request.host)
    end
     
    def redirect_to_cms_site
      if perform_caching && !cms_site?
        redirect_to(url_with_cms_domain_prefix)
      end
    end 
  
    def append_to_query_string(url, *params)
      new_url = url["?"] ? url : "#{url}?"
      new_url << params.map{|k,v| "#{k.to_s}=#{CGI::escape(v.to_s)}"}.join("&")
    end
  
    def cms_access_required
      raise Cms::Errors::AccessDenied unless current_user.able_to?(:administrate, :edit_content, :publish_content)
    end
  
    def self.check_permissions(*perms)
      opts = Hash === perms.last ? perms.pop : {}
      before_filter(opts) do |controller|
        raise Cms::Errors::AccessDenied unless controller.send(:current_user).able_to?(*perms)
      end      
    end
  
    def url_with_cms_domain_prefix
      if cms_site?
        request.url
      elsif request.subdomains.first == "www"
        request.url.sub(/www\./, "#{cms_domain_prefix}.")
      else
        request.url.sub(/:\/\//, "://#{cms_domain_prefix}.")
      end
    end
  
    def url_without_cms_domain_prefix
      request.url.sub(/#{cms_domain_prefix}\./,'')
    end
  
end

app/controllers/cms/attachments_controller.rb
class Cms::AttachmentsController < Cms::BaseController
  def show
    @attachment = Attachment.find(params[:id])
    @attachment = @attachment.as_of_version(params[:version]) if params[:version]
    send_file(@attachment.full_file_location, 
      :filename => @attachment.file_name,
      :type => @attachment.file_type,
      :disposition => "inline"
    )     
  end
end

app/controllers/cms/base_controller.rb
class Cms::BaseController < Cms::ApplicationController
  
  before_filter :redirect_to_cms_site
  before_filter :login_required
  before_filter :cms_access_required

  layout 'cms/application'
    
  verify :method => :post, :only => [:create]
  verify :method => :put, :only => [:update]
  verify :method => :delete, :only => [:destroy]
    
end

app/controllers/cms/cache_controller.rb
class Cms::CacheController < Cms::BaseController
  layout 'cms/administration'
  
  check_permissions :administrate  
  before_filter :set_menu_section

  def show
    
  end
  
  def destroy
    Cms.flush_cache
    flash[:notice] = "Page Cache Flushed"
    redirect_to :action => "show"
  end
  
  private
    def set_menu_section
      @menu_section = 'caching'
    end

end

app/controllers/cms/categories_controller.rb
class Cms::CategoriesController < Cms::ContentBlockController
  def show
    redirect_to cms_categories_url
  end
end

app/controllers/cms/category_types_controller.rb
class Cms::CategoryTypesController < Cms::ContentBlockController
  def show
    redirect_to cms_category_types_url
  end
end

app/controllers/cms/connectors_controller.rb
class Cms::ConnectorsController < Cms::BaseController
  
  before_filter :set_toolbar_tab
  before_filter :load_page, :only => [:new, :create]
  
  def new    
    @block_type = ContentType.find_by_key(params[:block_type] || session[:last_block_type] || 'html_block')
    @container = params[:container]
    @connector = @page.connectors.build(:container => @container)
    @blocks = @block_type.model_class.all(:order => "name", :conditions => ["deleted = ?", false])      
  end

  def create
    @block_type = ContentType.find_by_key(params[:connectable_type])
    raise "Unknown block type" unless @block_type
    @block = @block_type.model_class.find(params[:connectable_id])
    if @page.create_connector(@block, params[:container])
      redirect_to @page.path
    else
      @blocks = @block_type.model_class.all(:order => "name")      
      render :action => 'new'
    end
  end
  
  def destroy
    @connector = Connector.find(params[:id])
    @page = @connector.page
    @connectable = @connector.connectable
    if @page.remove_connector(@connector)
      flash[:notice] = "Removed '#{@connectable.name}' from the '#{@connector.container}' container"
    else
      flash[:error] = "Failed to remove '#{@connectable.name}' from the '#{@connector.container}' container"
    end
    redirect_to @page.path
  end

  { #Define actions for moving connectors around
    :up => "up in",
    :down => "down in",
    :to_top => "to the top of",
    :to_bottom => "to the bottom of"    
  }.each do |move, where|
    define_method "move_#{move}" do
      @connector = Connector.find(params[:id])
      @page = @connector.page
      @connectable = @connector.connectable
      if @page.send("move_connector_#{move}", @connector)
        flash[:notice] = "Moved '#{@connectable.name}' #{where} the '#{@connector.container}' container"
      else
        flash[:error] = "Failed to move '#{@connectable.name}' #{where} the '#{@connector.container}' container"
      end
      redirect_to @page.path    
    end
  end

  private
    def load_page
      @page = Page.find(params[:page_id])
    end
    def set_toolbar_tab
      @toolbar_tab = :content_library
    end
end

app/controllers/cms/content_block_controller.rb
# This is not called directly
# This is the base class for other content blocks
class Cms::ContentBlockController < Cms::BaseController
  
  layout :determine_layout
  
  before_filter :set_toolbar_tab
  
  helper_method :block_form, :new_block_path, :block_path, :blocks_path, :content_type
  helper Cms::RenderingHelper
  # Basic REST Crud Action
  
  def index
    load_blocks
    render "#{template_directory}/index"
  end
  
  def show
    load_block_draft
    render "#{template_directory}/show"
  end
  
  def new
    build_block
    set_default_category
    render "#{template_directory}/new"
  end
  
  def create
    if create_block
      after_create_on_success
    else
      after_create_on_failure
    end
  rescue Exception => @exception
    raise @exception if @exception.is_a?(Cms::Errors::AccessDenied)
    after_create_on_error
  end
  
  def edit
    load_block_draft
    render "#{template_directory}/edit"
  end
  
  def update
    if update_block
      after_update_on_success
    else
      after_update_on_failure
    end
  rescue ActiveRecord::StaleObjectError => @exception
    after_update_on_edit_conflict
  rescue Exception => @exception
    raise @exception if @exception.is_a?(Cms::Errors::AccessDenied)
    after_update_on_error
  end
  
  def destroy
    do_command("deleted") { @block.destroy }
    redirect_to_first params[:_redirect_to], blocks_path
  end
  
  # Additional CMS Action
  
  def publish
    do_command("published") { @block.publish! }
    redirect_to_first params[:_redirect_to], block_path
  end
  
  def revert_to
    do_command("reverted to version #{params[:version]}") do
      revert_block(params[:version])
    end
    redirect_to_first params[:_redirect_to], block_path
  end
  
  def version
    load_block
    if params[:version]
      @block = @block.as_of_version(params[:version])
    end
    render "#{template_directory}/show"
  end
  
  def versions
    if model_class.versioned?
      load_block
      render "#{template_directory}/versions"
    else
      render :text => "Not Implemented", :status => :not_implemented
    end    
  end
    
  def usages
    load_block_draft
    @pages = @block.connected_pages.all(:order => 'name')
    render "#{template_directory}/usages"
  end
  
  protected
    # methods that are used to detemine what content block type we are dealing with

    def content_type_name
      self.class.name.sub(/Controller/,'').demodulize.singularize
    end

    def content_type
      @content_type ||= ContentType.find_by_key(content_type_name)
    end  

    def model_class
      content_type.model_class
    end
  
    def model_name
      model_class.name.underscore.to_sym
    end
  
    # methods for loading one or a collection of blocks
  
    def load_blocks
      options = {}
      if params[:section_id] && params[:section_id] != 'all'
        options[:include] = { :attachment => { :section_node => :section }} 
        options[:conditions] = ["sections.id = ?", params[:section_id]]
      end
      options[:page] = params[:page]    
      options[:order] = model_class.default_order if model_class.respond_to?(:default_order)
      options[:order] = params[:order] unless params[:order].blank?
      scope = model_class.respond_to?(:list) ? model_class.list : model_class
      @blocks = scope.searchable? ? scope.search(params[:search]).paginate(options) : scope.paginate(options)
      check_permissions
    end
  
    def load_block
      @block = model_class.find(params[:id])
      check_permissions
    end
  
    def load_block_draft
      @block = model_class.find(params[:id])
      @block = @block.as_of_draft_version if model_class.versioned?
      check_permissions
    end
  
    # path related methods - available in the view as helpers
  
    def new_block_path(options={})
      cms_new_url_for(@block, options)
    end
  
    def block_path(action=nil)
      path = [:cms, @block]
      action ? path.unshift(action) : path
    end
  
    def blocks_path(options={})
      cms_index_url_for(@block, options)
    end

    # This is the partial that will be used in the form
    def block_form
      @content_type.form
    end
  
    # new related methods
  
    def build_block
      @block = model_class.new(params[model_name])
      check_permissions
    end

    def set_default_category
      if @last_block = model_class.last
        @block.category = @last_block.category if @block.respond_to?(:category=)
      end      
    end
    
    # create related methods
    
    def create_block
      build_block
      @block.save
    end

    def after_create_on_success
      block = @block.class.versioned? ? @block.draft : @block
      flash[:notice] = "#{content_type.display_name} '#{block.name}' was created"
      if @block.class.connectable? && @block.connected_page
        redirect_to @block.connected_page.path
      else
        redirect_to_first params[:_redirect_to], block_path
      end
    end

    def after_create_on_failure
      render "#{template_directory}/new"
    end

    def after_create_on_error
      logger.error "#{@exception.message}\n#{@exception.backtrace.join('\n')}"      
      after_create_on_failure
    end

    # update related methods
    def update_block
      load_block
      @block.update_attributes(params[model_name])
    end

    def after_update_on_success
      flash[:notice] = "#{content_type_name.titleize} '#{@block.name}' was updated"
      redirect_to_first params[:_redirect_to], block_path
    end

    def after_update_on_failure
      render "#{template_directory}/edit"
    end

    def after_update_on_edit_conflict
      @other_version = @block.class.find(@block.id)
      after_update_on_failure
    end

    def after_update_on_error
      logger.error "#{@exception.message}\n#{@exception.backtrace.join('\n')}"
      after_update_on_failure
    end

    # methods for other actions

    # A "command" is when you want to perform an action on a content block
    # You pass a ruby block to this method, this calls it
    # and then sets a flash message based on success or failure
    def do_command(result)
      load_block
      if yield
        flash[:notice] = "#{content_type_name.titleize} '#{@block.name}' was #{result}"
      else
        flash[:error] = "#{content_type_name.titleize} '#{@block.name}' could not be #{result}"
      end
    end

    def revert_block(to_version)
      begin
        @block.revert_to(to_version)
      rescue Exception => @exception
        logger.warn "Could not revert #{@block.inspect} to version #{to_version}"
        logger.warn "#{@exception.message}\n:#{@exception.backtrace.join("\n")}"
        false
      end
    end
    
    # Use a "whitelist" approach to access to avoid mistakes
    # By default everyone can create new block and view them and their properties,
    # but blocks can only be modified based on the permissions of the pages they
    # are connected to.
    def check_permissions
      case action_name
        when "index", "show", "new", "create", "version", "versions", "usages"
          # Allow
        when "edit", "update"
          raise Cms::Errors::AccessDenied unless current_user.able_to_edit?(@block)
        when "destroy", "publish", "revert_to"
          raise Cms::Errors::AccessDenied unless current_user.able_to_publish?(@block)
        else
          raise Cms::Errors::AccessDenied
      end
    end

    # methods to setup the view

    def set_toolbar_tab
      @toolbar_tab = :content_library
    end

    def determine_layout
      'cms/content_library'
    end

    def template_directory
      "cms/blocks"
    end

end

app/controllers/cms/content_types_controller.rb
class Cms::ContentTypesController < Cms::BaseController

  def index
    @content_types = ContentType.find(:all, :order => 'name')
  end
  
end

app/controllers/cms/dashboard_controller.rb
class Cms::DashboardController < Cms::BaseController
      
  def index
    @unpublished_pages = Page.unpublished.all(:order => "pages.updated_at desc")
    @unpublished_pages = @unpublished_pages.select { |page| current_user.able_to_publish?(page) }
    @incomplete_tasks = current_user.tasks.incomplete.all(
      :include => :page, 
      :order => "tasks.due_date desc, pages.name")
  end
end

app/controllers/cms/email_messages_controller.rb
class Cms::EmailMessagesController < Cms::BaseController
  layout 'cms/administration'
  
  check_permissions :administrate
  
  def index
    @messages = EmailMessage.paginate(:page => params[:page])
  end
  
  def show
    @message = EmailMessage.find(params[:id])
  end
  
end

app/controllers/cms/error_handling.rb
module Cms
  module ErrorHandling
    def self.included(controller)
      controller.class_eval do
        rescue_from Exception, :with => :handle_server_error unless RAILS_ENV == "test"
        rescue_from Cms::Errors::AccessDenied, :with => :handle_access_denied
      end
    end
    
    def handle_server_error(exception)
      logger.error "Handling Exception: #{exception}"
      render :layout => 'cms/application', 
        :template => 'cms/shared/error', 
        :status => :internal_server_error,
        :locals => {:exception => exception}
    end
    
    def handle_access_denied(exception)
      render :layout   => 'cms/application', 
             :template => 'cms/shared/access_denied',
             :status => 403
    end

  end
end

app/controllers/cms/file_blocks_controller.rb
class Cms::FileBlocksController < Cms::ContentBlockController
end

app/controllers/cms/home_controller.rb
class Cms::HomeController < Cms::BaseController
  def index
    redirect_to '/'
  end
end

app/controllers/cms/html_blocks_controller.rb
class Cms::HtmlBlocksController < Cms::ContentBlockController
end

app/views/cms/groups/_form.html.erb
<% content_for :html_head do %>
  <%= stylesheet_link_tag('cms/form_layout') %>
  <style type="text/css">
    .checkbox_group .checkboxes .instructions {
      padding-bottom: 10px;
    }
  </style>
  <% javascript_tag do %>
    jQuery(function($) {
      $('#group_group_type_id').selectbox();
    });
  <% end %>
<% end %>

<% content_for :functions do %> 
  <%= link_to(span_tag("List All"), cms_groups_path, 
    :id => "list_all_button", 
    :class => "button") %>
<% end %>

<% form_for [:cms, @group] do |f| %>

  <%= f.error_messages %>
  <div class="fields text_fields">
    <%= f.label :name, "Group Name" %>
    <%= f.text_field :name %>
  </div>

  <% unless @group.guest? %>
    <div class="fields select_fields">
    	<%= f.label :group_type_id, "Type of User" %>
    	<div><%= f.select :group_type_id, GroupType.non_guest.map { |g| [g.name, g.id] } %></div>
    	<div class="instructions">What kind of user does this group represent?</div>
  	<br clear="all" />
    </div>
  <% end %>

  <%= render :partial => 'permissions' %>
  <%= render :partial => 'sections' %>

  <div class="buttons">
    <%= lt_button_wrapper(f.submit("Save", :class => "submit")) %>
  </div>

<% end %>

app/views/cms/groups/_permissions.html.erb
<% content_for :html_head do %>
  <% javascript_tag do %>
    jQuery(function($){
      var cms_access_group_ids = <%= GroupType.cms_access.all.map{|e| e.id.to_s}.to_json %>
      $('#group_group_type_id').change(function() {
        if ($.inArray($('#group_group_type_id')[0].value, cms_access_group_ids) < 0) {
          $('#permissions').hide()
          $('#section-action').text('view')
        } else {
          $('#permissions').show()
          $('#section-action').text('edit')          
        }
      }).change()      
    });
  <% end %>
<% end %>
<div id="permissions">
  <div class="checkbox_group">
    <label>Global Permissions</label>
    <%= hidden_field_tag "group[permission_ids][]", "" %>  
    <div class="checkboxes">
    <% Permission.all(:order => "name").each do |p| %>
      <div class="checkbox_fields">
          <%= check_box_tag "group[permission_ids][]", p.id, @group.permissions.include?(p), :id => "permission_ids_#{p.id}", :class => "permission_ids" %>
          <label for="permission_ids_<%= p.id %>" style="width: 400px;#padding-top: 6px;"><%=h p.full_name %></label>
      </div>
      <div class="instructions"><%=h p.description %></div>
    <% end %>
    <div class="check_uncheck">
  	  <%= link_to_check_all 'input.permission_ids' %>, 
  	  <%= link_to_uncheck_all 'input.permission_ids' %>
    </div>
  </div>
    <br clear="all" />
  <div style="clear: all; margin-top: -10px;"></div>
    </div>
</div>

app/views/cms/groups/_sections.html.erb
<div class="checkbox_group fields">
  <label>Section Permissions</label>
  <%= hidden_field_tag "group[section_ids][]", "" %>
  <div class="checkboxes">
  <% Section.all(:order => "path").each do |s|%>
  <div class="checkbox_fields">
    <%= check_box_tag "group[section_ids][]", s.id, @group.sections.include?(s), :id => "section_ids_#{s.id}", :class => "section_ids" %>
    <label for= "section_ids_<%= s.id %>" style="width: 400px; padding-top: 0; #padding-top: 4px;"><%=h s.name %><span style="padding-top: 0; font-weight: lighter; display: inline; float: none;">(Path: <%=h s.path %>)</span></label>
  </div>
  <% end %>
  <div class="instructions">What sections should group members be allowed to <span id="section-action"><%= @group.cms_access? ? 'edit' : 'view' %></span>?</div>
  <div class="check_uncheck">
    <%= link_to_check_all 'input.section_ids' %>, 
    <%= link_to_uncheck_all 'input.section_ids' %>
  </div>
  </div>
  <br clear="all" />
  <div style="clear: all;"></div>
</div>

app/views/cms/groups/edit.html.erb
<% page_title "Administration / Add New Group" %>
<% @toolbar_title = "Add New Group" %>

<%= render :partial => 'form' %>

app/views/cms/groups/index.html.erb
<% page_title "Administration / Group Browser" %>
<% @toolbar_title = "List Groups" %>

<% content_for :functions do %> 
  <%= link_to(span_tag("Add Group"), new_cms_group_path, 
    :id => "new_group_button", :class => "button") %>
<% end %>

<div class="roundedcorners">
  <table class="data">
    <thead>
      <tr>
        <th colspan="2" class="first">
          <div class="dividers">
            <%= link_to "Name", cms_groups_path(:order => determine_order(params[:order], "groups.name")) %>
          </div>
        </th>
        <th>
          <div class="dividers">
            <%= link_to "Type", cms_groups_path(:order => determine_order(params[:order], "group_types.name")) %>
          </div>
        </th>
        <th colspan="2" class="last"><div class="dividers">Permissions</div></th>
      </tr>
    </thead>
    <% section_count = Section.count %>
    <% @groups.each do |g| %>
      <tr>
        <td class="first"></td>
        <td>
          <div class="dividers">
            <%= link_to h(g.name), [:edit, :cms, g] %>
          </div>
        </td>
        <td>
          <div class="dividers">
            <%= h(g.group_type.name) %>
          </div>
        </td>
        <td>
          <% g.permissions.uniq.each do |p| %>
            - <%= p.full_name %> <br />
          <% end %>
          - <%= g.cms_access? ? "Edit" : "View" %>
          <%= g.sections.count >= section_count ? "All Sections" : "#{g.sections.count} of #{section_count} Sections" %>
        </td>
        <td class="last"></td>
      </tr>
    <% end %>
  </table>
  <div class="tl"></div>
  <div class="tr"></div>
  <div class="bl"></div>
  <div class="br"></div>
</div>
<% if @groups.total_pages > 1 %>
  <%= render_pagination @groups, :groups %>
<% end %>

app/views/cms/groups/new.html.erb
<% page_title "Administration / Add New Group" %>
<% @toolbar_title = "Add New Group" %>

<%= render :partial => 'form' %>